export const SET_USERNAME = 'SET_USERNAME';
export const SET_ROOMNAME = 'SET_ROOMNAME';
export const SET_MESSAGE = 'SET_MESSAGE';
export const SET_MSG_LIST = 'PUSH_MSG_LIST';
export const SEND_MESSAGE = 'SOCKET_SEND_MSG';

export const SOCKET_SEND_USERNAME = 'SOCKET_SEND_USERNAME';
export const SOCKET_SEND_MESSAGE = 'SOCKET_SEND_MESSAGE';
export const SOCKET_SEND_ROOMNAME = 'SOCKET_SEND_ROOMNAME';

export const VALID_USERNAME = 'VALID_USERNAME';

export const SOCKET_RECV_MESSAGE = 'SOCKET_RECV_MESSAGE';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SOCKET_SEND_MSG = 'SOCKET_SEND_MSG';
export const SOCKET_JOIN_ROOM = 'SOCKET_JOIN_ROOM';

export const ADD_MULTIPLES_MESSAGES = 'ADD_MULTIPLES_MESSAGES';